name: 'Merge'
description: 'Merge a head to a branch'
inputs:
  target_branch:
    description: 'Target branch'
    required: true
  source_branch:
    description: 'Source branch'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
