name: 'Merge'
description: 'Merge a head to a branch'
inputs:
  target_branch:
    description: 'Target branch (e.g. develop)'
    required: true
  commit_sha:
    description: 'Source commit, use ${{ github.sha }}'
    required: true
  repository:
    description: 'Repository path, use ${{ github.repository }}'
    required: true
  github_token:
    description: 'GitHub token, use ${{ secrets.GITHUB_TOKEN }}'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
